export type AdminType = {
    certificate_push_limit: number,
    city: string,
    created_at:  string  |    null,
    deleted_at:  string  |    null,
    deleted_by:  string  |    null,
    designation: string |   null,
    email: string,
    emailLimitRemaining: number,
    emails_limit: number,
    id: number,
    name: string,
    official_email: string,
    organization_name: string,
    phone: null | string,
    profile_image: null | string,
    updated_at: null | string,
    website: string | null,
}