export type UserType = {
    createdBy: {},
    created_at: string | null,
    deletedAt: string | null,
    deletedBy: string | number | null,
    fields: Record<string, string> | null,
    gender: string | null,
    id: number,
    mobile_number: string | null,
    name: string,
    profile_image: string | null,
    updatedAt: string | null,
    updatedBy: {},
    userTags: {}[],
    year_of_birth: string | null,
};